spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.lakwppzkqyoymaakghuz
spring.datasource.password=LautaroRocco
spring.datasource.driver-class-name=org.postgresql.Driver

# Desactiva el caché de las vistas de forma estricta
spring.mustache.cache=false
# Evita que el backend Java se reinicie al modificar HTML o CSS
spring.devtools.restart.exclude=templates/**,static/**